---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services
# icons found here https://github.com/walkxcode/dashboard-icons

- Hypervisor:
    - Proxmox:
        icon: proxmox.svg
        href: "{{HOMEPAGE_VAR_PROXMOX_URL}}"
        description: pve
        widget:
            type: proxmox
            url: "{{HOMEPAGE_VAR_PROXMOX_URL}}"
            username:  "{{HOMEPAGE_VAR_PROXMOX_USER}}"
            password:  "{{HOMEPAGE_VAR_PROXMOX_API_KEY}}"
            node: pve
    - Proxmox:
        icon: proxmox.svg
        href: "{{HOMEPAGE_VAR_PROXMOX_URL}}"
        description: pve1
        widget:
            type: proxmox
            url: "{{HOMEPAGE_VAR_PROXMOX_URL}}"
            username:  "{{HOMEPAGE_VAR_PROXMOX_USER}}"
            password:  "{{HOMEPAGE_VAR_PROXMOX_API_KEY}}"
            node: pve1
- Containers:
    - Portainer:
        icon: portainer.svg
        href: "{{HOMEPAGE_VAR_PORTAINER_URL}}"
        description: docker
        widget:
            type: portainer
            url: "{{HOMEPAGE_VAR_PORTAINER_URL}}"
            env: 3
            key: "{{HOMEPAGE_VAR_PORTAINER_API_KEY}}"
    
- DNS:
    - Pi-Hole:
        icon: pi-hole.svg
        href: "{{HOMEPAGE_VAR_PIHOLE_URL}}"
        description: DNS
        widget:
            type: pihole
            url: "{{HOMEPAGE_VAR_PIHOLE_URL}}"
            version: 6
            key: "{{HOMEPAGE_VAR_PIHOLE_API_KEY}}"

- Network:
    # - UniFi:
    #     icon: unifi.svg
    #     href: "{{HOMEPAGE_VAR_UNIFI_NETWORK_URL}}"
    #     description: network
    #     widget:
    #         type: unifi
    #         url: "{{HOMEPAGE_VAR_UNIFI_NETWORK_URL}}"
    #         username:  "{{HOMEPAGE_VAR_UNIFI_NETWORK_USERNAME}}"
    #         password:  "{{HOMEPAGE_VAR_UNIFI_NETWORK_PASSWORD}}"
    - Uptime Kuma:
        icon: uptime-kuma.svg
        href: "{{HOMEPAGE_VAR_UPTIME_KUMA_URL}}"
        description: internal
        widget:
            type: uptimekuma
            url: "{{HOMEPAGE_VAR_UPTIME_KUMA_URL}}"
            slug: home
    
# - Storage:
#     - TrueNAS:
#         icon: truenas.svg
#         href: "{{HOMEPAGE_VAR_TRUENAS_URL}}"
#         description: scale
#         widget:
#             type: truenas
#             url: "{{HOMEPAGE_VAR_TRUENAS_URL}}"
#             key: "{{HOMEPAGE_VAR_TRUENAS_API_KEY}}"

- Media:
    - Jellyfin:
        icon: jellyfin.svg
        href: "{{HOMEPAGE_VAR_JELLYFIN_URL}}"
        description: media server
        widget:
            type: jellyfin
            url: "{{HOMEPAGE_VAR_JELLYFIN_URL}}"
            key: "{{HOMEPAGE_VAR_JELLYFIN_API_TOKEN}}"
    
- Remote Access:
    - Tailscale:
        icon: tailscale.svg
        href: "{{HOMEPAGE_VAR_TAILSCALE_URL}}"
        description: tailscale
        widget:
            type: tailscale
            url: "{{HOMEPAGE_VAR_TAILSCALE_URL}}"

- Home Automation:
    - Home Assistant:
        icon: home-assistant.svg
        href: "{{HOMEPAGE_VAR_HOME_ASSISTANT_URL}}"
        description: home
        widget:
            type: homeassistant
            url: "{{HOMEPAGE_VAR_HOME_ASSISTANT_URL}}"
            key: "{{HOMEPAGE_VAR_HOME_ASSISTANT_API_KEY}}"
- Other:
    - GitHub:
        icon: github.svg
        href: https://github.com
        description: source code
    
