---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services
# icons found here https://github.com/walkxcode/dashboard-icons

- Hypervisor:
    - Proxmox:
        icon: proxmox.svg
        href: "{{HOMEPAGE_VAR_PROXMOX_URL}}"
        description: pve
        widget:
          type: proxmox
          url: "{{HOMEPAGE_VAR_PROXMOX_URL}}"
          username: "{{HOMEPAGE_VAR_PROXMOX_USER}}"
          password: "{{HOMEPAGE_VAR_PROXMOX_API_KEY}}"
          node: pve
    - Proxmox:
        icon: proxmox.svg
        href: "{{HOMEPAGE_VAR_PROXMOX_URL}}"
        description: pve1
        widget:
          type: proxmox
          url: "{{HOMEPAGE_VAR_PROXMOX_URL}}"
          username: "{{HOMEPAGE_VAR_PROXMOX_USER}}"
          password: "{{HOMEPAGE_VAR_PROXMOX_API_KEY}}"
          node: pve1

- Containers:
    - Portainer:
        icon: portainer.svg
        href: "{{HOMEPAGE_VAR_PORTAINER_URL}}"
        description: docker
        widget:
          type: portainer
          url: "{{HOMEPAGE_VAR_PORTAINER_URL}}"
          env: 3
          key: "{{HOMEPAGE_VAR_PORTAINER_API_KEY}}"

- DNS:
    - Pi-Hole:
        icon: pi-hole.svg
        href: "{{HOMEPAGE_VAR_PIHOLE_URL}}"
        description: DNS
        widget:
          type: pihole
          url: "{{HOMEPAGE_VAR_PIHOLE_URL}}"
          version: 6
          key: "{{HOMEPAGE_VAR_PIHOLE_API_KEY}}"

- Network:
    - Omada:
        icon: omada.svg
        href: "{{HOMEPAGE_VAR_OMADA_NETWORK_URL}}"
        description: network
        widget:
          type: omada
          url: "{{HOMEPAGE_VAR_OMADA_NETWORK_URL}}"
          username: "{{HOMEPAGE_VAR_OMADA_NETWORK_USERNAME}}"
          password: "{{HOMEPAGE_VAR_OMADA_NETWORK_PASSWORD}}"
          site: The Hogs Head
    - Myspeed:
        icon: myspeed.svg
        href: http://192.168.0.103:5216/
        description: speed test
        widget:
          type: myspeed
          url: http://192.168.0.103:5216/

    - Uptime Kuma:
        icon: uptime-kuma.svg
        href: "{{HOMEPAGE_VAR_UPTIME_KUMA_URL}}"
        description: internal
        widget:
          type: uptimekuma
          url: "{{HOMEPAGE_VAR_UPTIME_KUMA_URL}}"
          slug: homelab

# - Storage:
#     - TrueNAS:
#         icon: truenas.svg
#         href: "{{HOMEPAGE_VAR_TRUENAS_URL}}"
#         description: scale
#         widget:
#             type: truenas
#             url: "{{HOMEPAGE_VAR_TRUENAS_URL}}"
#             key: "{{HOMEPAGE_VAR_TRUENAS_API_KEY}}"

- Media:
    - Jellyfin:
        icon: jellyfin.svg
        href: "{{HOMEPAGE_VAR_JELLYFIN_URL}}"
        description: media server
        widget:
          type: jellyfin
          url: "{{HOMEPAGE_VAR_JELLYFIN_URL}}"
          key: "{{HOMEPAGE_VAR_JELLYFIN_API_TOKEN}}"
    - Jellyseerr:
        icon: jellyseerr.svg
        href: "{{HOMEPAGE_VAR_JELLYSEERR_URL}}"
        description: media requests
        widget:
          type: jellyseerr
          url: "{{HOMEPAGE_VAR_JELLYSEERR_URL}}"
          key: "{{HOMEPAGE_VAR_JELLYSEERR_API_KEY}}"
    - Automated Ripping Machine:
        icon: arm.svg
        href: "{{HOMEPAGE_VAR_ARM_URL}}"
        description: media ripping
        # widget:
        #   type: arm
        #   url: "{{HOMEPAGE_VAR_ARM_URL}}"
        #   key: "{{HOMEPAGE_VAR_ARM_API_KEY}}"

- Arr:
    - Radarr:
        icon: radarr.svg
        href: "{{HOMEPAGE_VAR_RADARR_URL}}"
        description: movies
        widget:
          type: radarr
          url: "{{HOMEPAGE_VAR_RADARR_URL}}"
          key: "{{HOMEPAGE_VAR_RADARR_API_KEY}}"

    - Sonarr:
        icon: sonarr.svg
        href: "{{HOMEPAGE_VAR_SONARR_URL}}"
        description: tv shows
        widget:
          type: sonarr
          url: "{{HOMEPAGE_VAR_SONARR_URL}}"
          key: "{{HOMEPAGE_VAR_SONARR_API_KEY}}"

    - Bazarr:
        icon: bazarr.svg
        href: "{{HOMEPAGE_VAR_BAZARR_URL}}"
        description: subtitles
        widget:
          type: bazarr
          url: "{{HOMEPAGE_VAR_BAZARR_URL}}"
          key: "{{HOMEPAGE_VAR_BAZARR_API_KEY}}"

    - Prowlarr:
        icon: prowlarr.svg
        href: "{{HOMEPAGE_VAR_PROWLARR_URL}}"
        description: indexers
        widget:
          type: prowlarr
          url: "{{HOMEPAGE_VAR_PROWLARR_URL}}"
          key: "{{HOMEPAGE_VAR_PROWLARR_API_KEY}}"

    - Tdarr:
        icon: tdarr.svg
        href: "{{HOMEPAGE_VAR_TDARR_URL}}"
        description: media transcoding
        # widget:
        #   type: tdarr
        #   url: "{{HOMEPAGE_VAR_TDARR_URL}}"
        #   key: "{{HOMEPAGE_VAR_TDARR_API_KEY}}"

    - qBittorrent:
        icon: qbittorrent.svg
        href: "{{HOMEPAGE_VAR_QBITTORRENT_URL}}"
        description: torrent client
        widget:
          type: qbittorrent
          url: "{{HOMEPAGE_VAR_QBITTORRENT_URL}}"
          username: "{{HOMEPAGE_VAR_QBITTORRENT_USERNAME}}"
          password: "{{HOMEPAGE_VAR_QBITTORRENT_PASSWORD}}"
          enableLeechProgress: true
          enableDownloadProgress: true

- Remote Access:
    - Tailscale:
        icon: tailscale.svg
        href: https://tailscale.com/admin/machines
        description: tailscale

- Home Automation:
    - Home Assistant:
        icon: home-assistant.svg
        href: "{{HOMEPAGE_VAR_HOME_ASSISTANT_URL}}"
        description: home
        # widget:
        #     type: homeassistant
        #     url: "{{HOMEPAGE_VAR_HOME_ASSISTANT_URL}}"
        #     key: "{{HOMEPAGE_VAR_HOME_ASSISTANT_API_KEY}}"
- Other:
    - GitHub:
        icon: github.svg
        href: https://github.com/jcnichols22
        description: source code
